### ISSUE TITLE
Maybe I found why the Copy to clipboard does not work

### ISSUE THREAD

**Issue by hick** [SeptemberHX/screenshot#1]
I am not so familiar with PyQT, but know a little something, so I do not know exact the way to correct this problem

after calling the saveScreenshot function, you do  "self.close()" to close current App, this maybe cause the "Gabage Collection", including something about the clipboard.  

I tried to comment the "self.close()", and pressed button "o", then I pressed alt + tab to switch to a MS word window (thought I can only imagine that,  I can not see that window for mask from this app), I pressed ctrl + v ,   then ESC to quit this app,  I saw the screenshot in MS word :)

so maybe there is a way not to close this app but to clean the screen mask,  let this app always to be running, maybe it works

![image](https://cloud.githubusercontent.com/assets/38886/16160615/c4289a24-34fb-11e6-9dbd-e4ffb19df873.png)

**Comment by hick** [comment]
I got some more about it,  replacing the self.close() to self.resize(0, 0)  works.

I realized that it's not a mask, it is the app's fullscreen window  :)

**Comment by SeptemberHX** [comment]
Still I can't find a way to keep the image in clipboard after mainwindow closed.
What I can do is keep the mainwindow longer enough, so we have enough time to paste the image :)
