### ISSUE TITLE
在windows10上面 python3.7.5  截图后 点勾勾 程序就退出了

### ISSUE THREAD

**Issue by zhoujin7** [SeptemberHX/screenshot#3]
在windows10上面 python3.7.5  截图后 点勾勾 程序就退出了
```
======>>> 1920, 1080

Process finished with exit code -1073740791 (0xC0000409)
```

**Comment by SeptemberHX** [comment]
点勾勾之后，剪贴板里有东西吗？

**Comment by zhoujin7** [comment]
> 点勾勾之后，剪贴板里有东西吗？

剪贴板没有东西

**Comment by SeptemberHX** [comment]
运行的是 Screenshot.py 还是 demo.py ? 还是说两个都有这样的问题？

**Comment by zhoujin7** [comment]
> 运行的是 Screenshot.py 还是 demo.py ? 还是说两个都有这样的问题？

这两个都一样 都有问题 , 用的pyqt5 pip源里面的最新版
直接在pycharm里面运行.

**Comment by zhoujin7** [comment]
![1](https://user-images.githubusercontent.com/8288988/77151610-42d22980-6ad1-11ea-9fd9-fa0467714967.gif)

而且有个小问题 ,  启动的时候, colorbar和另外一个widget会闪一下, 两个白框框, 然后消失.  gif里面没录到.

**Comment by zhoujin7** [comment]
还有一个问题哈, 在windows10上面 双显示屏 貌似是有问题的. 只能在主屏上截图. 看来作者不用windows...

**Comment by SeptemberHX** [comment]
后期我是在Windows上开发的，我的也是 pip 源里的 pyqt5 5.14.1，但是我这边运行没有问题。

~~能不能在 pycharm 里用 debug 模式运行一下？如果有错误的话会正常显示出来，不会只输出exit code这种。~~    我找到问题了，已提交

然后多屏幕的话，因为我没有想好怎么样才能够像其它截屏软件那样同时在屏幕显示多个屏幕截图——因为我的逻辑是截一个屏幕，然后放到一个全屏的widget里，这样问题就来了，全屏只能在一个屏幕全屏。所以目前的逻辑是只会截取程序窗口的那个屏幕，所以你可以试着把pycharm放到另外一个屏幕，然后运行应该就能在那个屏幕上工作。你有啥好的想法不？

**Comment by zhoujin7** [comment]
![image](https://user-images.githubusercontent.com/8288988/77159753-e545d900-6ae0-11ea-90fe-92b14403f5a5.png)
我重新下载了 可以运行了 有结果了 只是那个窗口很小 没根据图片尺寸适应而已

**Comment by SeptemberHX** [comment]
因为是个demo，就没写最外面的 QLabel 自适应，这个 demo 是想演示能够通过一个函数来获得截图对象。粘贴板里应该已经有了，QLabel 自行放大也可以看到截图内容

**Comment by zhoujin7** [comment]
> 后期我是在Windows上开发的，我的也是 pip 源里的 pyqt5 5.14.1，但是我这边运行没有问题。
> 
> ~能不能在 pycharm 里用 debug 模式运行一下？如果有错误的话会正常显示出来，不会只输出exit code这种。~ 我找到问题了，已提交
> 
> 然后多屏幕的话，因为我没有想好怎么样才能够像其它截屏软件那样同时在屏幕显示多个屏幕截图——因为我的逻辑是截一个屏幕，然后放到一个全屏的widget里，这样问题就来了，全屏只能在一个屏幕全屏。所以目前的逻辑是只会截取程序窗口的那个屏幕，所以你可以试着把pycharm放到另外一个屏幕，然后运行应该就能在那个屏幕上工作。你有啥好的想法不？

这有个QT的开源截屏工具, 我不会cpp, 所以没有下载运行确定它是否支持多屏. 应该没考虑跨平台, 不过可以参考.
https://blog.csdn.net/CSND_Ayo/article/details/70197915
https://gitee.com/Mr_ChenLuYong/screenshot

这个是确定支持多屏的, QT开源项目, 跨平台支持.
https://github.com/ksnip/ksnip

其他, csharp写的, 支持多屏.
https://github.com/ShareX

**Comment by SeptemberHX** [comment]
好的，多谢

**Comment by zhoujin7** [comment]
https://github.com/teyying/PyQt5_Demo/tree/master/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE/SC
这个不会出现一闪而过的白框框

**Comment by zhoujin7** [comment]
> 
> 然后多屏幕的话，因为我没有想好怎么样才能够像其它截屏软件那样同时在屏幕显示多个屏幕截图——因为我的逻辑是截一个屏幕，然后放到一个全屏的widget里，这样问题就来了，全屏只能在一个屏幕全屏。所以目前的逻辑是只会截取程序窗口的那个屏幕，所以你可以试着把pycharm放到另外一个屏幕，然后运行应该就能在那个屏幕上工作。你有啥好的想法不？

全屏只能在一个屏幕全屏 --> 这个貌似不对吧 
多屏, 扩展屏幕模式, 多个屏幕组成了一个虚拟的大屏幕, 不是单独的, 都在同一个坐标体系下.
按现有的思路应该可以做到吧. 我猜的哈.

**Comment by zhoujin7** [comment]
> > 然后多屏幕的话，因为我没有想好怎么样才能够像其它截屏软件那样同时在屏幕显示多个屏幕截图——因为我的逻辑是截一个屏幕，然后放到一个全屏的widget里，这样问题就来了，全屏只能在一个屏幕全屏。所以目前的逻辑是只会截取程序窗口的那个屏幕，所以你可以试着把pycharm放到另外一个屏幕，然后运行应该就能在那个屏幕上工作。你有啥好的想法不？
> 
> 全屏只能在一个屏幕全屏 --> 这个貌似不对吧
> 多屏, 扩展屏幕模式, 多个屏幕组成了一个虚拟的大屏幕, 不是单独的, 都在同一个坐标体系下.
> 按现有的思路应该可以做到吧. 我猜的哈.

https://github.com/gilyes/Screenshot.NET 就是这么实现的, 先截图整个虚拟大屏幕. 
![image](https://user-images.githubusercontent.com/8288988/77165174-c1889000-6aec-11ea-9922-a724159ae7a7.png)
QT里面也可以这么做. QScreen 
https://www.ics.com/blog/whats-new-qt-5-qscreen-class
 virtual geometry

**Comment by SeptemberHX** [comment]
我看看是怎么实现的，因为虚拟屏幕的话，如果两个屏幕分辨率不一致，那应该不能很简单的虚拟出来了

**Comment by zhoujin7** [comment]
> 我看看是怎么实现的，因为虚拟屏幕的话，如果两个屏幕分辨率不一致，那应该不能很简单的虚拟出来了

两个屏幕不一样大没事的, 按最大的屏幕来, 大小不足的留黑(或透明), 其他截图软件是这样做的.
当然我只是说说哈, 代码还是很难的, 我就搞不定......
![image](https://user-images.githubusercontent.com/8288988/77222684-6a3bfb80-6b90-11ea-88af-6bf29867a148.png)

**Comment by SeptemberHX** [comment]
看起来有戏，我研究研究

**Comment by zhoujin7** [comment]
> 看起来有戏，我研究研究

"虚拟屏幕尺寸", QT自带了这个api, windows form/wpf 也自带了这个api
```python
a=QGuiApplication.screens()[0] #0肯定存在, 如果存在两个屏幕, 1和0得到的结果是一样的, 肯定都一样
print(a.virtualGeometry())
print(a.virtualSize())
```

**Comment by zhoujin7** [comment]
> 看起来有戏，我研究研究

这个太折腾了哈, 我刚刚测试了, 在第二个屏幕上用pycharm运行代码, 发现工具栏跑到第一个屏幕上了.
我弃坑了, 我现在只要能在单独的每个屏幕上能正常的选取截图就行了, 不强求能一次截取所有屏幕, 而且也不要求能像qq截图那样出现放大镜之类的东西, 这个我能自己改好.
😂😂😂
抄代码好难~~看了几个开源的程序, 好复杂`~~`

**Comment by SeptemberHX** [comment]
抛开hidpi和多屏幕不看的话，其实就是一个画板，如果不加redo、undo功能的话，那基本上就是调用 Qt 已经提供好的函数。都想实现的话就有点复杂了，我一开始写的时候也很乱。
